"""Unique name on oauth client

Revision ID: 295195036f83
Revises: 512db52065be
Create Date: 2020-11-01 11:08:11.844752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295195036f83'
down_revision = '512db52065be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('name_user_id_unique_1', 'oauth2_clients', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('name_user_id_unique_1', 'oauth2_clients', type_='unique')
    # ### end Alembic commands ###
