"""Adds OAuth2Client

Revision ID: 49403f9c4712
Revises: 54c65032340e
Create Date: 2020-10-24 19:39:54.833096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49403f9c4712'
down_revision = '54c65032340e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth2_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('client_secret', sa.String(length=96), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('secret_expires_at', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth2_clients_client_id'), 'oauth2_clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_oauth2_clients_client_secret'), 'oauth2_clients', ['client_secret'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth2_clients_client_secret'), table_name='oauth2_clients')
    op.drop_index(op.f('ix_oauth2_clients_client_id'), table_name='oauth2_clients')
    op.drop_table('oauth2_clients')
    # ### end Alembic commands ###
