"""Add name field to auth2 client

Revision ID: 512db52065be
Revises: 23510b4bc3d0
Create Date: 2020-11-01 00:45:40.148883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512db52065be'
down_revision = '23510b4bc3d0'
branch_labels = None
depends_on = None

## This won't work if you already have multiple clients per user

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth2_clients', sa.Column('name', sa.String(length=100), nullable=True))
    op.execute("UPDATE oauth2_clients SET name='primary'")
    op.alter_column('oauth2_clients', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth2_clients', 'name')
    # ### end Alembic commands ###
